version: "3.9"
services:
  students-api-db:
    image: postgres:13.1
    container_name: students-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ${PWD}/docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "6652:5432"
    expose:
      - 6652

  students-api:
    depends_on:
      - students-api-db
    image: students-api-1.0:latest
    container_name: students-api-1.0
    environment:
      ENV: docker
    ports:
      - "8930:8080"